apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-java-runtime-image
spec:
  description: |
    S2I Java Runtime Image Build Pipeline
  resources:
    - name: intermediate-image
      type: image
    - name: runtime-image
      type: image
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git branch to clone.
    - name: namespace
      type: string
      description: Namespace where you will be deploying the app (used in configmap)
    - name: application
      type: string
      description: Name of the application (used in configmap)
    - name: target_environment
      type: string
      description: Is it development/test/production?
    - name: RUNTIME_BASE_IMAGE
      description: Base image to build the runtime image
      default: docker.io/openliberty/open-liberty:22.0.0.4-full-java17-openj9
    - name: SOURCE_ARTIFACT_TO_COPY_1
      description: Source artifact to copy onto the runtime image
      default: /deployments/liberty-rest-app.war
    - name: TARGET_LOCATION_ARTIFACT_1
      description: Destination for the source artifact
      default: /config/apps/liberty-rest-app.war
    - name: SOURCE_ARTIFACT_TO_COPY_2
      description: Source artifact to copy onto the runtime image
      default: /deployments/config
    - name: TARGET_LOCATION_ARTIFACT_2
      description: Destination for the source artifact
      default: /config/
    - name: S2I_SOURCE_DEPLOYMENTS_FILTER
      description: Files we are deploying
      default: '*.war'
    - name: JAVA_IMAGESTREAM_URL
      description: Java Imagestream Url
      default: 'image-registry.openshift-image-registry.svc:5000/openshift/openjdk-17:latest'
    - name: MAVEN_ARGS_APPEND
      description: Maven additional arguments
      default: ""
    - name: MAVEN_S2I_GOALS
      description: Maven goals to run
      default: liberty:package package
    - name: S2I_SOURCE_DATA_DIR
      description: Libraries to copy over along with other artifacts
      default: "target/liberty/wlp/usr/servers/defaultServer/libraries"
    - name: S2I_TARGET_DATA_DIR
      description: Libraries to copy over along with other artifacts - target
      default: "/deployments/libraries/"
    - name: SOURCE_ARTIFACT_TO_COPY_3
      description: Source artifact to copy onto the runtime image
      default: /deployments/libraries
    - name: TARGET_LOCATION_ARTIFACT_3
      description: Destination for the source artifact
      default: /opt/ol/wlp/usr/servers/defaultServer/libraries/
  workspaces:
    - name: intermediate-docker-image-pvc
      description: |
        Intermediate Docker Image will be here
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
    - name: build
      taskRef:
        kind: Task
        name: s2i-java
      workspaces:
        - name: source
          workspace: shared-data
        - name: intermediate-docker-image-pvc
          workspace: intermediate-docker-image-pvc
      params:
        - name: MAVEN_ARGS_APPEND
          value: $(params.MAVEN_ARGS_APPEND)
        - name: S2I_SOURCE_DEPLOYMENTS_FILTER
          value: $(params.S2I_SOURCE_DEPLOYMENTS_FILTER)
        - name: JAVA_IMAGESTREAM_URL
          value: $(params.JAVA_IMAGESTREAM_URL)
        - name: MAVEN_S2I_GOALS
          value: $(params.MAVEN_S2I_GOALS)
        - name: S2I_SOURCE_DATA_DIR
          value: $(params.S2I_SOURCE_DATA_DIR)
        - name: S2I_TARGET_DATA_DIR
          value: $(params.S2I_TARGET_DATA_DIR)
      resources:
        outputs:
        - name: intermediate-image
          resource: intermediate-image
      runAfter:
        - fetch-repo
    - name: create-runtime-image
      taskRef:
        kind: Task
        name: create-runtime-image
      workspaces:
        - name: source
          workspace: shared-data
        - name: intermediate-docker-image-pvc
          workspace: intermediate-docker-image-pvc
      params:
        - name: pipelineRunName
          value: $(context.pipelineRun.name)
        - name: pipelineName
          value: $(context.pipeline.name)
        - name: RUNTIME_BASE_IMAGE
          value: $(params.RUNTIME_BASE_IMAGE)
        - name: SOURCE_ARTIFACT_TO_COPY_1
          value: $(params.SOURCE_ARTIFACT_TO_COPY_1)
        - name: TARGET_LOCATION_ARTIFACT_1
          value: $(params.TARGET_LOCATION_ARTIFACT_1)
        - name: SOURCE_ARTIFACT_TO_COPY_2
          value: $(params.SOURCE_ARTIFACT_TO_COPY_2)
        - name: TARGET_LOCATION_ARTIFACT_2
          value: $(params.TARGET_LOCATION_ARTIFACT_2)
        - name: SOURCE_ARTIFACT_TO_COPY_3
          value: $(params.SOURCE_ARTIFACT_TO_COPY_3)
        - name: TARGET_LOCATION_ARTIFACT_3
          value: $(params.TARGET_LOCATION_ARTIFACT_3)
      resources:
        inputs:
          - name: intermediate-image
            resource: intermediate-image
        outputs:
          - name: runtime-image
            resource: runtime-image
      runAfter:
        - build
    # oc adm create-kubeconfig --client-certificate=/path/to/client.crt --client-key=/path/to/client.key --certificate-authority=/path/to/ca.crt            
    - name: set-configmaps
      taskRef:
        kind: Task
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: shared-data
      runAfter:
        - create-runtime-image
      params:
        - name: SCRIPT
          value: |
            oc create -n $(params.namespace) configmap $(params.application)-env-configdropins --from-file=config/$(params.target_environment)/configDropins

