apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-java-runtime-image
spec:
  description: |
    S2I Java Runtime Image Build Pipeline
  resources:
    - name: intermediate-image
      type: image
    - name: runtime-image
      type: image
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git branch to clone.
  workspaces:
    - name: intermediate-docker-image-pvc
      description: |
        Intermediate Docker Image will be here
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
    - name: build
      taskRef:
        kind: Task
        name: s2i-java
      workspaces:
        - name: source
          workspace: shared-data
        - name: intermediate-docker-image-pvc
          workspace: intermediate-docker-image-pvc
      params:
        - name: MAVEN_ARGS_APPEND
          value: ""
      resources:
        outputs:
        - name: intermediate-image
          resource: intermediate-image
      runAfter:
        - fetch-repo
    - name: create-runtime-image
      taskRef:
        kind: Task
        name: create-runtime-image
      workspaces:
        - name: source
          workspace: shared-data
        - name: intermediate-docker-image-pvc
          workspace: intermediate-docker-image-pvc
      params:
        - name: pipelineRunName
          value: $(context.pipelineRun.name)
        - name: pipelineName
          value: $(context.pipeline.name)
      resources:
        inputs:
          - name: intermediate-image
            resource: intermediate-image
        outputs:
          - name: runtime-image
            resource: runtime-image
      runAfter:
        - build
